### ISSUE TITLE
Generate shareable links

### ISSUE THREAD

**Issue by nishidhaSri** [nishidhaSri/spacestagram#1]
- Users can only like and dislike the space images currently. 
- New feature to be added where they can easily copy/share the link of images by clicking the share button below each image.

**Comment by arvind-1** [comment]
@nishidhaSri Can I work on this? or you suggest

**Comment by nishidhaSri** [comment]
Sure, @arvind-1 go ahead and give it a try.

**Comment by arvind-1** [comment]
@nishidhaSri could you assign this to me?

**Comment by arvind-1** [comment]
I have few questions.
1. As we are fetching this directly from NASA API we don't have our id for each image. what do we do about it?
2. If user access the shared link how do they view that image as a single image with comments or description about it? 
3. Should we maintain our own database?

**Comment by nishidhaSri** [comment]
Regarding your query:

1. Every image have a unique URL, so we can differentiate using that
2. This I am leaving it to your creativity, you can either create new route for each APOD image where more detail information like description is shown and this route can be shared or just provide a way where user can directly share the image url. Ultimate goal is to share the image.
3. This project is created to enhance frontend skills, lets consider using databases or writing apis as a last resort.

**Comment by arvind-1** [comment]
About every image having a unique URL, they are for API right now our APP?

**Comment by nishidhaSri** [comment]
I mean the source url of the image which is received in every object of APOD

**Comment by arvind-1** [comment]
Yes, but how do fetch that image from share? there is no unique identifier for that image apart from the URL. So we have to make our own indexing for these images.
For example, if we have a sharable URL as https://spacestagram/img/1345 with this URL we need to scrap image from API and we don't have any APIs to fetch data.

**Comment by nishidhaSri** [comment]
APOD have a unique date for every image, go through the queries accepted by API used, you can fetch APOD by date

**Comment by kailash360** [comment]
Can I work on this issue?

**Comment by nishidhaSri** [comment]
sure @kailash360

**Comment by kailash360** [comment]
@nishidhaSri, I have created the PR #10 for this issue.

**Comment by nishidhaSri** [comment]
Do create a PR to development branch

**Comment by kailash360** [comment]
@nishidhaSri, I have now a created PR #12 in the development branch.
