### ISSUE TITLE
New loader component

### ISSUE THREAD

**Issue by nishidhaSri** [nishidhaSri/spacestagram#2]
- Currently more images are loaded while showing "Load More" text
- New creative loader can be a great addition to the project

**Comment by harishfalco** [comment]
Hi nishidhaSri, Can you assign it to me? I am ready to work on this.]

**Comment by nishidhaSri** [comment]
Sure, go ahead @harishfalco. Looking for a creative perspective here.

**Comment by kailash360** [comment]
I want to work on this issue @nishidhaSri

**Comment by nishidhaSri** [comment]
Sure, go ahead. Make sure the loader aligns with the UI already developed

**Comment by kailash360** [comment]
I have created PR #8 for this issue
