### ISSUE TITLE
UI Bug

### ISSUE THREAD

**Issue by nishidhaSri** [nishidhaSri/spacestagram#3]
- Liked icon goes on top of the navigation bar
- Check image below for a better understanding

![Spacestagram - Opera 28-09-2021 17_35_52](https://user-images.githubusercontent.com/44313138/135083674-87ef489a-6c76-47a0-9b16-713e8db305fb.png)

**Comment by harishfalco** [comment]
I think you are pointing out the red color like button right? can you provide more details on where it should come and assign it to me?

**Comment by arvind-1** [comment]
fixed this one.

**Comment by nishidhaSri** [comment]
Merged, bug resolved
