### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by nishidhaSri** [nishidhaSri/spacestagram#4]
- Only toggle is present currently to activate dark mode.
- Yet to be designed and developed

**Comment by kailash360** [comment]
I would like to work on this issue

**Comment by nishidhaSri** [comment]
Sure, go ahead. Assigning this issue to you @kailash360

**Comment by kailash360** [comment]
I have created a PR #7 for this issue

**Comment by nishidhaSri** [comment]
Will review @kailash360
